# This file was generated by GoReleaser. DO NOT EDIT.
cask "markfluence" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "8ecb238c729d6381c84fc239eaf6f043723a191834472163545ed9b15d51c417"
      url "https://github.com/mozilla/markfluence/releases/download/v#{version}/markfluence_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ae5c0e202c36058fb01ff6a01e761310ed7bfad5c99400961169fa4c32eb296e"
      url "https://github.com/mozilla/markfluence/releases/download/v#{version}/markfluence_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1b89b7b40592af65fab28681a2284842ff1ace4df720049fbb8788ce004dca84"
      url "https://github.com/mozilla/markfluence/releases/download/v#{version}/markfluence_#{version}_linux_amd64.tar.gz"
    end
  end

  name "markfluence"
  desc "CLI for publishing and manipulating Confluence pages from Markdown"
  homepage "https://github.com/mozilla/markfluence"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "markfluence"
  bash_completion "completions/markfluence.bash"
  fish_completion "completions/markfluence.fish"
  zsh_completion "completions/markfluence.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/markfluence"]
    end
  end

  # No zap stanza required
end
