# This file was generated by GoReleaser. DO NOT EDIT.
cask "markfluence" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "dd3e8308852b830d3da0c1ff49d63f9ef3bacc3a8c29b1844cf418340dd4e5a3"
      url "https://github.com/mozilla/markfluence/releases/download/v#{version}/markfluence_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9067dae6d88ae4542130e96223ec23a5ac761e9295cdd76b3cf7d917e70e63d8"
      url "https://github.com/mozilla/markfluence/releases/download/v#{version}/markfluence_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e34d37e7ea2d2f6b2c4d4692f4e22f1ecf59e529cac269466c657f2a2da6cb98"
      url "https://github.com/mozilla/markfluence/releases/download/v#{version}/markfluence_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "939b22be2ce6a18bc20865287aaf1b270fa5566f6f1af84832d2cfe94650cf7c"
      url "https://github.com/mozilla/markfluence/releases/download/v#{version}/markfluence_#{version}_linux_amd64.tar.gz"
    end
  end

  name "markfluence"
  desc "CLI for publishing and manipulating Confluence pages from markdown"
  homepage "https://github.com/mozilla/markfluence"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "markfluence"
  bash_completion "completions/markfluence.bash"
  fish_completion "completions/markfluence.fish"
  zsh_completion "completions/markfluence.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/markfluence"]
    end
  end

  # No zap stanza required
end
