# This file was generated by GoReleaser. DO NOT EDIT.
cask "markfluence" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "da4367596d29ab71497b39ac582eab6f23f8dc7a6bda92c59d6be4189c88f8de"
      url "https://github.com/mozilla/markfluence/releases/download/v#{version}/markfluence_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1782bbeec2390be7b09df13e9fa316dbf4617c2f9e4068aa6c3ad651c8de84e7"
      url "https://github.com/mozilla/markfluence/releases/download/v#{version}/markfluence_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "82088479878d1dcdf5fcc6d0afeff3bc5129682948a6682771b558d5cba73478"
      url "https://github.com/mozilla/markfluence/releases/download/v#{version}/markfluence_#{version}_linux_amd64.tar.gz"
    end
  end

  name "markfluence"
  desc "CLI for publishing and manipulating Confluence pages from Markdown"
  homepage "https://github.com/mozilla/markfluence"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "markfluence"
  bash_completion "completions/markfluence.bash"
  fish_completion "completions/markfluence.fish"
  zsh_completion "completions/markfluence.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/markfluence"]
    end
  end

  # No zap stanza required
end
